### ISSUE TITLE
Passing a variable as permission

### ISSUE THREAD

**Issue by ITEANJD** [AlexKhymenko/ngx-permissions#87]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

element doesn't switch its status (from invisible to visible or vice versa) if the permissions are dynamic.

if I have a button like this:
` <button *ngxPermissionsOnly="some_permissions"> add Button</button>`
some_permissions is a variable which changes as the route changes, the button save its status and doesn't switch on or off.

## Expected behavior

the DOM element must change its status as the variable changes.

## Minimal reproduction of the problem with instructions

https://next.plnkr.co/edit/BQp2g8oDSCQ3MCRmSfqK?p=preview&preview

## Environment

<pre><code>
Angular version: 6.2.5
ngx-permissions version: 6.0.2

Browser:
- [x] Chrome (desktop) version 70.0
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
@ITEANJD Thank You. WIll fix it next week.

**Comment by AlexKhymenko** [comment]
@ITEANJD Fixed in 6.0.3.

**Comment by AlexKhymenko** [comment]
@ITEANJD Fix it in version 6.0.4

**Comment by ITEANJD** [comment]
I'm still having some issues with it.

what I have:
- parent component with "Add button"
- each children component is accessible using routes like _products_, _roles_, etc...

what I do in parent component:
- take the route _products_, remove last character so it's "product" then add a prefix store, so I ended up with **store_product**
- store this **store_product** as string or array in variable, let's call it 'permissions'.
- add that last variable as permissions to the "Add button" in the parent component

current behavior:
- let's say I have **store_product** permission, but not **store_role**
- if I open _roles_ route, the button is invisible
- if I route to _products_, the button is visible as expected
- but if I route to _roles_ again, I see the button although it must be invisible.

I would like to reproduce it, but if you got the bug, you are going to save my time ^^

Thanks in advance.

**Comment by ITEANJD** [comment]
I think it works, but I'm going to test it more
then I will tell you if it works as expected.
